[package]
name = "days-counter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.54"


[lib]
name = "days_counter"
path = "src/lib.rs"

[[bin]]
name = "days_counter"
path = "src/main.rs"
